"""自定义渲染器示例：GetProcAddress thunk 表风格。

用法：
    python fakedll.py header xxx.dll -o xxx_thunks.h --renderer renderers/getproc_thunk.py

生成的头文件不声明导入函数，而是为每个导出生成
    extern FARPROC name_thunk;    // 运行时由 GetProcAddress 填充
    #define name ((t_##name)name_thunk)
配合 usage() 给出的初始化函数，避免静态链接 —— 适合
给"缺失 DLL 的程序"做运行时兜底（LoadLibrary 失败也可用替代实现填充）。

可作为自定义渲染逻辑的模板：render(ctx) 返回整个文件内容，
ctx.functions 每个元素是 fakedll.analyze.FunctionFacts。
"""

from __future__ import annotations

CC_TYPE = {
    "__cdecl": "__cdecl",
    "__stdcall": "__stdcall",
    "__fastcall": "__fastcall",
    # x64 / 未知：不写调用约定关键字
}


def _ptr_type(ctx, f, name) -> str:
    """构造函数指针类型：void* (__cdecl *NAME)(void* p1, ...)"""
    if ctx.bits == 64:
        cc = ""
    else:
        cc = CC_TYPE.get(f.convention or "__cdecl", "")
    n = f.param_count
    if n is None or n == 0:
        params = "void"
    else:
        params = ", ".join(f"void* p{i + 1}" for i in range(n))
    if cc:
        return f"void* ({cc} *{name})({params})"
    return f"void* (*{name})({params})"


def render(ctx) -> str:
    L: list[str] = []
    ap = L.append

    st = ctx.stats()
    funcs = [f for f in ctx.functions if not f.is_data and not f.export.forwarder]
    datas = [f for f in ctx.functions if f.is_data]

    guard = f"{ctx.dll_name.upper()}_THUNKS_H_"
    ap("/*")
    ap(f" * {ctx.dll_name}.dll GetProcAddress thunk 表")
    ap(f" * Generated by fakedll (custom renderer: getproc_thunk) on {ctx.generated_at}")
    ap(f" * Source: {ctx.dll_path} ({ctx.bits}-bit {ctx.machine})")
    ap(f" * {st['total']} exports -> {len(funcs)} functions, {len(datas)} data")
    ap(" */")
    ap("")
    ap(f"#ifndef {guard}")
    ap(f"#define {guard}")
    ap("")
    ap("#include <windows.h>")
    ap("")
    ap("/* ---- 函数指针类型 ---- */")
    for f in funcs:
        ap(f"typedef {_ptr_type(ctx, f, f't_{f.clean_name}')};")
    ap("")
    ap("/* ---- 运行时填充的 thunk 槽位 ---- */")
    for f in funcs:
        ap(f"extern t_{f.clean_name} {f.clean_name}_thunk;")
    for f in datas:
        ap(f"extern void* {f.clean_name};  /* data export */")
    ap("")
    ap("/* ---- 便捷宏：像普通函数一样调用 ---- */")
    for f in funcs:
        ap(f"#define {f.clean_name} ({f.clean_name}_thunk)")
    ap("")
    ap("/* ---- 初始化：从真实 DLL 填充全部槽位 ---- */")
    ap(f"static int {ctx.dll_name}_init_thunks(HMODULE mod)")
    ap("{")
    ap("    int missing = 0;")
    for f in funcs:
        name = f.export.name or f"#{f.export.ordinal}"
        ap(f"    {f.clean_name}_thunk = (t_{f.clean_name})GetProcAddress(mod, \"{name}\");")
        ap(f"    if (!{f.clean_name}_thunk) missing++;")
    for f in datas:
        name = f.export.name or f"#{f.export.ordinal}"
        ap(f"    {f.clean_name} = (void*)GetProcAddress(mod, \"{name}\");")
        ap(f"    if (!{f.clean_name}) missing++;")
    ap("    return missing; /* 返回缺失的导出个数，0 = 全部就绪 */")
    ap("}")
    ap("")
    ap(f"#endif /* {guard} */")
    ap("")
    return "\n".join(L)


def usage() -> str:
    """fakedll 调用 --list-renderers 时展示的说明（可选）。"""
    return "生成 GetProcAddress 运行时 thunk 表头文件"
